### ISSUE TITLE
could not download all labels if the shipment contains multiple packages "multi_piece_shipment"

### ISSUE THREAD

**Issue by rga-odoo** [goshippo/shippo-python-client#72]
Hi 
I am following this example https://github.com/goshippo/shippo-python-client/blob/master/examples/multi_piece_shipment.py

The parcel contains multiple packages/pieces and wants to print the label of all the pieces but API returns only the first label. 
In web interface there is also one label to download but when I click on the tracking link there tracking code for all packages

**Comment by jfriedr** [comment]
@rga-odoo Have you ensured you are viewing all the labels in this specific line we're essentially doing a GET (passing a rate object_id):

[    for num,label in enumerate(transactions.results)](https://github.com/goshippo/shippo-python-client/blob/efec396c837e7c5cb3853d3ff60fd645104fe8e1/examples/multi_piece_shipment.py#L123)

Feel free to comment here if you need any additional help on this.  Apologies this issue was left up so long with a proper response.
